server:  port: 8800  servlet:    context-path: /paipai
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paipai?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver\    